version: '2'
services:
    arq-app:
        image: arq
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://arq-postgresql:5432/arq
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    arq-postgresql:
        extends:
            file: postgresql.yml
            service: arq-postgresql
